<?php
use Drupal\Core\Form\FormStateInterface;
use Stephane888\Debug\debugLog;
use Drupal\user\Entity\Role;

/**
 *
 * @file
 * Primary module hooks for layoutrestrictions module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_form_FORM_ID_alter() for the entity view display edit form.
 */
function layoutrestrictions_form_layout_builder_configure_section_alter(&$form, FormStateInterface &$form_state, $form_id) {
  debugLog::kintDebugDrupal($form['layout_settings'], 'layout_builder_configure_section_alter', true);
  if (!empty($form['layout_settings'])) {
    $form['layout_settings']['layoutrestrictions'] = [
      
      '#type' => 'details',
      '#title' => 'layout restrictions',
      '#open' => false,
      '#tree' => true
    ];
    $roles = [];
    foreach (Role::loadMultiple() as $role) {
      $roles[$role->id()] = $role->label();
    }
    $form['layout_settings']['layoutrestrictions']['roles'] = [
      '#type' => 'checkboxes',
      '#title' => 'selectionner les roles',
      '#options' => $roles
    ];
  }
}